### ISSUE TITLE
[Feature Request] Input file to yaml

### ISSUE THREAD

**Issue by jochettino** [juanjnc/clonehoot#1]
Hey! I was taking a look at it (no deeply yet, sorry) and the input file you propose in the README file is a little old-school fashion.

What about replacing it with a yaml file? It would be easier to read. You could have something more semantical like

```
clonehoot:
  questions:
    - question: blabla
      answer1: bleble
      answer2: ...
      answer3: ...
      answer4: ...
      correctAnswer: 1
    - question: awesome question
      ...
```

Yaml is a widely used format to configure services, apps... So I'm sure you'll find a Python library to read it easily.

Regards!
